apiVersion: v1
kind: Service
metadata:
  name: esp-echo
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: esp-echo
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esp-echo
spec:
  selector:
    matchLabels:
      app: esp-echo
  template:
    metadata:
      labels:
        app: esp-echo
    spec:
      containers:
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http2_port=9000",
            "--service=echo.v1.endpoints.dd-test-endpoint.cloud.goog",
            "--rollout_strategy=managed",
            "--backend=grpc://127.0.0.1:50051",
          ]
          ports:
            - containerPort: 9000
        - name: echo
          image: gcr.io/dd-test-endpoint/echo:1.0
          ports:
            - containerPort: 50051

